### ISSUE TITLE
1.16.4??

### ISSUE THREAD

**Issue by theoparis** [JAD3N/mc-wrench#1]
Can you get a 1.16.4 version done? I really like this mod but it doesn't work on 1.16.4 because its for 1.16.1 only

**Comment by JAD3N** [comment]
Just pushed a fix (4ddbcd77cbd20ebd9a1674741b114142c9f6ac1c), I'll publish it shortly to CurseForge after testing.

**Comment by JAD3N** [comment]
After fixing another issue and testing the update, everything seems good. I've submitted the update to CurseForge and they are now processing the file and it should be available to download shortly.
